name: CI-CD catalogs-handler

on:
    push:
        branches:
            - main

env: 
    IMAGE_NAME: catalogs-handler-739204
    CONTAINER_REGISTRY: 932065333859.dkr.ecr.us-east-1.amazonaws.com/catalogs-handler-739204

    AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
    CLIENTS_TABLE_NAME: ${{ vars.CLIENTS_TABLE_NAME }}
    PRODUCTS_TABLE_NAME: ${{ vars.PRODUCTS_TABLE_NAME }}
    ADDRESSES_TABLE_NAME: ${{ vars.ADDRESSES_TABLE_NAME }}

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build Docker image
              run: |
                docker build -t ${{ env.CONTAINER_REGISTRY }}:latest .

            - name: Push Docker image to ECR
              run: |
                docker push ${{ env.CONTAINER_REGISTRY }}:latest

            - name: SSH into EC2 and deploy Docker container
              run : |
                mkdir -p ~/.ssh
                echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

                ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF

                    docker stop catalogs-handler-739204 || true
                    docker rm catalogs-handler-739204 || true

                    docker pull ${{ env.CONTAINER_REGISTRY }}:latest

                    docker run -d --name catalogs-handler-739204 \
                    -e AWS_BUCKET_NAME=${{ env.AWS_BUCKET_NAME }} \
                    -e CLIENTS_TABLE_NAME=${{ env.CLIENTS_TABLE_NAME }} \
                    -e PRODUCTS_TABLE_NAME=${{ env.PRODUCTS_TABLE_NAME }} \
                    -e ADDRESSES_TABLE_NAME=${{ env.ADDRESSES_TABLE_NAME }} \
                    -p 3001:3001 \
                    ${{ env.CONTAINER_REGISTRY }}:latest

                    docker logs catalogs-handler-739204
                EOF