name: CI-CD catalogs-handler

on:
    push:
        branches:
            - main

env: 
    IMAGE_NAME: catalogs-handler-739204
    CONTAINER_REGISTRY: 932065333859.dkr.ecr.us-east-1.amazonaws.com/catalogs-handler-739204

    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

    AWS_BUCKET_NAME: ${{ vars. AWS_BUCKET_NAME }}
    CLIENTS_TABLE_NAME: ${{ vars.CLIENTS_TABLE_NAME }}
    PRODUCTS_TABLE_NAME: ${{ vars.PRODUCTS_TABLE_NAME }}
    ADDRESSES_TABLE_NAME: ${{ vars.ADDRESSES_TABLE_NAME }}

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build Docker image
              run: |
                docker build -t ${{ steps.login-ecr.outputs.registry }}/catalogs-handler-739204:latest .

            - name: Push Docker image to ECR
              run: |
                docker push ${{ steps.login-ecr.outputs.registry }}/catalogs-handler-739204:latest
